### ISSUE TITLE
Small typo on the Updating Models section

### ISSUE THREAD

**Issue by Eusebiotrigo** [Interactions-as-a-Service/docs#1]
In https://docs.interactions.rest/d1-orm/models#updating-data

It states this method receives 2 parameters, where in fact it is only one, "options", with 2 properties, `where` and `data`.

The usage would be:
```ts
await users.Update({ 
   where: { email: "john-doe@gmail.com" } , 
   data: { name: "Jane Doe" }
});
```

instead of:
```ts
await users.Update({ where: { name: "Jane Doe" } }, { name: "John Doe" });
```

I could raise a PR to make the change if you wish.

**Comment by Eusebiotrigo** [comment]
It was fixed as part of https://github.com/Interactions-as-a-Service/docs/commit/46174bf213decb4d10828ab78ff59a355fb36755

**Comment by Skye-31** [comment]
Not sure how I missed your report, sorry 😅
Glad it's solved now
